apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["amsc-d3/postgres"]'
    management.cattle.io/ui-managed: 'true'
    nersc.gov/clustername: production
    nersc.gov/collab_uids: '102407'
    nersc.gov/gid: '81687'
    nersc.gov/gids: 4871,61512,59322,72330,81687,81765,74560,96414,103452,103453,113529
    nersc.gov/roles: user
    nersc.gov/serveralias: svc
    nersc.gov/uid: '81687'
    nersc.gov/username: esseivaj
  creationTimestamp: '2026-03-09T18:27:35Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/targetWorkloadIds: {}
            f:management.cattle.io/ui-managed: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"bb2d364f-0e6e-408d-8d0a-80e288f35830"}: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":5432,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2026-03-09T18:27:35Z'
  name: postgres
  namespace: amsc-d3
  ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: postgres
      uid: bb2d364f-0e6e-408d-8d0a-80e288f35830
  resourceVersion: '1128128825'
  uid: a0caf0c0-77f1-4d6c-a3d4-bbd13bcc8a30
spec:
  clusterIP: 10.43.124.69
  clusterIPs:
    - 10.43.124.69
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-amsc-d3-postgres
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
