apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '5'
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["128.55.206.106"],"port":443,"protocol":"HTTPS","serviceName":"amsc-d3:grafana","ingressName":"amsc-d3:ingress","hostname":"amsc-d3.ml4phys.com","path":"/grafana","allNodes":true},{"addresses":["128.55.206.106"],"port":443,"protocol":"HTTPS","serviceName":"amsc-d3:grafana","ingressName":"amsc-d3:ingress","hostname":"ingress.amsc-d3.production.svc.spin.nersc.org","path":"/grafana","allNodes":true}]
    nersc.gov/collab_uids: '102407'
    nersc.gov/gid: '81687'
    nersc.gov/gids: 4871,61512,59322,72330,81687,81765,74560,96414,103452,103453,113529
    nersc.gov/roles: user
    nersc.gov/uid: '81687'
    nersc.gov/username: esseivaj
  creationTimestamp: '2026-03-09T23:39:05Z'
  generation: 10
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-amsc-d3-grafana
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:field.cattle.io/publicEndpoints: {}
          f:labels:
            .: {}
            f:workload.user.cattle.io/workloadselector: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:workload.user.cattle.io/workloadselector: {}
              f:namespace: {}
            f:spec:
              f:containers:
                k:{"name":"container-0"}:
                  .: {}
                  f:env:
                    .: {}
                    k:{"name":"GF_DISABLE_SANITIZE_HTML"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"GF_SERVER_ROOT_URL"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"GF_SERVER_SERVE_FROM_SUB_PATH"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"KUBERNETES_CLUSTER_DOMAIN"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":3000,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:name: {}
                      f:protocol: {}
                  f:resources: {}
                  f:securityContext:
                    .: {}
                    f:allowPrivilegeEscalation: {}
                    f:capabilities:
                      .: {}
                      f:drop: {}
                    f:privileged: {}
                    f:readOnlyRootFilesystem: {}
                    f:runAsNonRoot: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/var/lib/grafana"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
              f:volumes:
                .: {}
                k:{"name":"vol-0sdem"}:
                  .: {}
                  f:name: {}
                  f:persistentVolumeClaim:
                    .: {}
                    f:claimName: {}
      manager: agent
      operation: Update
      time: '2026-03-10T21:50:18Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2026-03-10T21:50:21Z'
  name: grafana
  namespace: amsc-d3
  resourceVersion: '1128787761'
  uid: 0177acd2-2116-43d2-bd77-5b66735fcc37
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-amsc-d3-grafana
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        nersc.gov/collab_uids: '102407'
        nersc.gov/gid: '81687'
        nersc.gov/gids: 4871,61512,59322,72330,81687,81765,74560,96414,103452,103453,113529
        nersc.gov/roles: user
        nersc.gov/uid: '81687'
        nersc.gov/username: esseivaj
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-amsc-d3-grafana
      namespace: amsc-d3
    spec:
      containers:
        - env:
            - name: GF_DISABLE_SANITIZE_HTML
              value: 'true'
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: cluster.local
            - name: GF_SERVER_ROOT_URL
              value: '%(protocol)s://%(domain)s/grafana'
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: 'true'
          image: grafana/grafana-oss:11.6.0
          imagePullPolicy: Always
          name: container-0
          ports:
            - containerPort: 3000
              name: grafana
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: vol-0sdem
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: vol-0sdem
          persistentVolumeClaim:
            claimName: grafana-store
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2026-03-09T23:39:05Z'
      lastUpdateTime: '2026-03-10T21:28:15Z'
      message: ReplicaSet "grafana-76cf588c64" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2026-03-10T21:50:21Z'
      lastUpdateTime: '2026-03-10T21:50:21Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
  observedGeneration: 10
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
