apiVersion: v1
kind: Service
metadata:
  annotations:
    nersc.gov/clustername: production
    nersc.gov/collab_uids: '102407'
    nersc.gov/gid: '81687'
    nersc.gov/gids: 4871,61512,59322,72330,81687,81765,74560,96414,103452,103453
    nersc.gov/roles: user
    nersc.gov/serveralias: svc
    nersc.gov/uid: '81687'
    nersc.gov/username: esseivaj
  creationTimestamp: '2026-01-28T22:17:00Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":9097,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":9191,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2026-01-29T23:26:34Z'
  name: envoy-service
  namespace: amsc-d3
  resourceVersion: '1104667548'
  uid: a60ee3e8-236a-4ef7-93f2-69864bde831a
spec:
  clusterIP: 10.43.158.200
  clusterIPs:
    - 10.43.158.200
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: grpc
      port: 9097
      protocol: TCP
      targetPort: 9097
    - name: admin
      port: 9191
      protocol: TCP
      targetPort: 9191
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-amsc-d3-envoy-proxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
