apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '10'
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["128.55.206.106"],"port":80,"protocol":"HTTP","serviceName":"amsc-d3:remote-triton-controller","ingressName":"amsc-d3:api-server","hostname":"api-server.amsc-d3.production.svc.spin.nersc.org","path":"/","allNodes":true}]
    nersc.gov/collab_uids: '102407'
    nersc.gov/gid: '81687'
    nersc.gov/gids: 4871,61512,59322,72330,81687,81765,74560,96414,103452,103453,113529
    nersc.gov/roles: user
    nersc.gov/uid: '81687'
    nersc.gov/username: esseivaj
  creationTimestamp: '2026-03-04T18:25:11Z'
  generation: 15
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-amsc-d3-remote-triton-controller
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:field.cattle.io/publicEndpoints: {}
          f:labels:
            .: {}
            f:workload.user.cattle.io/workloadselector: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:annotations:
                f:cattle.io/timestamp: {}
              f:labels:
                .: {}
                f:workload.user.cattle.io/workloadselector: {}
              f:namespace: {}
            f:spec:
              f:containers:
                k:{"name":"container-0"}:
                  .: {}
                  f:env:
                    .: {}
                    k:{"name":"CONTROLLER_API_TOKEN"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:secretKeyRef: {}
                    k:{"name":"IRI_ACCESS_TOKEN"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:secretKeyRef: {}
                    k:{"name":"POSTGRES_DB"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:secretKeyRef: {}
                    k:{"name":"POSTGRES_HOST"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"POSTGRES_PASSWORD"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:secretKeyRef: {}
                    k:{"name":"POSTGRES_PORT"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"POSTGRES_USER"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:secretKeyRef: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":8080,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:name: {}
                      f:protocol: {}
                  f:resources: {}
                  f:securityContext:
                    .: {}
                    f:allowPrivilegeEscalation: {}
                    f:capabilities:
                      .: {}
                      f:drop: {}
                    f:privileged: {}
                    f:readOnlyRootFilesystem: {}
                    f:runAsNonRoot: {}
                    f:runAsUser: {}
                  f:stdin: {}
                  f:stdinOnce: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:tty: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/config"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                    k:{"mountPath":"/kube-config"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext:
                .: {}
                f:fsGroup: {}
              f:serviceAccount: {}
              f:serviceAccountName: {}
              f:terminationGracePeriodSeconds: {}
              f:volumes:
                .: {}
                k:{"name":"vol-ilzla"}:
                  .: {}
                  f:name: {}
                  f:secret:
                    .: {}
                    f:defaultMode: {}
                    f:optional: {}
                    f:secretName: {}
                k:{"name":"vol-ngdmc"}:
                  .: {}
                  f:hostPath:
                    .: {}
                    f:path: {}
                    f:type: {}
                  f:name: {}
      manager: agent
      operation: Update
      time: '2026-03-10T00:20:55Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2026-03-10T00:20:59Z'
  name: remote-triton-controller
  namespace: amsc-d3
  resourceVersion: '1128271345'
  uid: 2a269945-e81c-43ba-a3d2-fe6e66cd391e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-amsc-d3-remote-triton-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2026-03-10T00:20:55Z'
        nersc.gov/collab_uids: '102407'
        nersc.gov/gid: '81687'
        nersc.gov/gids: 4871,61512,59322,72330,81687,81765,74560,96414,103452,103453,113529
        nersc.gov/roles: user
        nersc.gov/uid: '81687'
        nersc.gov/username: esseivaj
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-amsc-d3-remote-triton-controller
      namespace: amsc-d3
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: REMOTE_TRITON_DB_NAME
                  name: postgress-password
                  optional: false
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: REMOTE_TRITON_DB_USER
                  name: postgress-password
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: REMOTE_TRITON_DB_PASSWORD
                  name: postgress-password
                  optional: false
            - name: POSTGRES_HOST
              value: postgres
            - name: IRI_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: IRI_ACCESS_TOKEN
                  name: iri-token
                  optional: false
            - name: CONTROLLER_API_TOKEN
              valueFrom:
                secretKeyRef:
                  key: api-auth-token
                  name: api-auth-token
                  optional: false
            - name: POSTGRES_PORT
              value: '5432'
          image: esseivaj/remote-triton-controller:0.1.3
          imagePullPolicy: Always
          name: container-0
          ports:
            - containerPort: 8080
              name: api-server
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 81687
          stdin: true
          stdinOnce: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /kube-config
              name: vol-ilzla
            - mountPath: /config
              name: vol-ngdmc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 74560
        runAsGroup: 74560
        runAsUser: 81687
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - name: vol-ilzla
          secret:
            defaultMode: 420
            optional: false
            secretName: kubeconfig
        - hostPath:
            path: /global/cfs/cdirs/m2845/amsc-d3/triton-controller
            type: Directory
          name: vol-ngdmc
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2026-03-10T00:15:11Z'
      lastUpdateTime: '2026-03-10T00:15:11Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2026-03-10T00:15:19Z'
      lastUpdateTime: '2026-03-10T00:20:59Z'
      message: >-
        ReplicaSet "remote-triton-controller-5f86b75dcd" has successfully
        progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 15
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
