apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["amsc-d3/remote-triton-controller"]'
    management.cattle.io/ui-managed: 'true'
    nersc.gov/clustername: production
    nersc.gov/collab_uids: '102407'
    nersc.gov/gid: '81687'
    nersc.gov/gids: 4871,61512,59322,72330,81687,81765,74560,96414,103452,103453,113529
    nersc.gov/roles: user
    nersc.gov/serveralias: svc
    nersc.gov/uid: '81687'
    nersc.gov/username: esseivaj
  creationTimestamp: '2026-03-09T19:40:48Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/targetWorkloadIds: {}
            f:management.cattle.io/ui-managed: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"2a269945-e81c-43ba-a3d2-fe6e66cd391e"}: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8080,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2026-03-09T19:40:48Z'
  name: remote-triton-controller
  namespace: amsc-d3
  ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: remote-triton-controller
      uid: 2a269945-e81c-43ba-a3d2-fe6e66cd391e
  resourceVersion: '1128158322'
  uid: 259c5724-18b8-4439-bbba-6fdf61965b76
spec:
  clusterIP: 10.43.213.114
  clusterIPs:
    - 10.43.213.114
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: api-server
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-amsc-d3-remote-triton-controller
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
