# prometheus iaas-metrics
# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: envoy
    metrics_path: /stats/prometheus
    static_configs:
      - targets: ['envoy-service.amsc-d3.svc.cluster.local:9191']

  - job_name: triton
    metrics_path: /metrics
    http_sd_configs:
      - url: http://remote-triton-controller.amsc-d3.svc.cluster.local:8080/api/sd/prometheus
        refresh_interval: 15s
