apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["amsc-d3/prometheus"]'
    management.cattle.io/ui-managed: 'true'
    nersc.gov/clustername: production
    nersc.gov/collab_uids: '102407'
    nersc.gov/gid: '81687'
    nersc.gov/gids: 4871,61512,59322,72330,81687,81765,74560,96414,103452,103453,113529
    nersc.gov/roles: user
    nersc.gov/serveralias: svc
    nersc.gov/uid: '81687'
    nersc.gov/username: esseivaj
  creationTimestamp: '2026-03-09T20:04:21Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/targetWorkloadIds: {}
            f:management.cattle.io/ui-managed: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"352ce96f-6fe7-4f3d-bfc1-71051c4f2ead"}: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":9090,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2026-03-09T20:04:21Z'
  name: prometheus
  namespace: amsc-d3
  ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: prometheus
      uid: 352ce96f-6fe7-4f3d-bfc1-71051c4f2ead
  resourceVersion: '1128167806'
  uid: 105ea323-48aa-40fd-9e2f-394a47f2f76f
spec:
  clusterIP: 10.43.248.61
  clusterIPs:
    - 10.43.248.61
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: prometheus
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-amsc-d3-prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
